# Generated by Django 3.0.3 on 2020-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20200413_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
